load "../Code/BruteForcePoints.m";
load "../Code/Cascade.m";

B, C, n := Explode([29,3,3]);
K<s> := QuadraticField(-B);
OK := Integers(K);
CK , CKmap := ClassGroup(K);

O := FindOrder(B,C,K,OK);
picO, mO := PicardGroup(O);

print "The class group of OK is Z/6Z: ",IsIsomorphic(CK, AbelianGroup([6]));
print "The class group of OK is generated by an ideal above 3: ", Order((CKmap^(-1))(Factorization(3*OK)[1][1])) eq 6;
print "There are no admissible twists: ", #AdmissibleTwists(B,C,n) eq 0;
print "We do not find points by brute force (up to ht=5000): ", #FindOnePointUpToHeight(B,C,n:height := 5000) eq 0; 